---
- name: Create control plane config directory
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /var/lib/kubernetes 
    - /etc/kubernetes/config

- name: Run this command to generate a random key used for the var "encryption_key"
  shell: head -c 32 /dev/urandom | base64
  register: encryption_key_cmd

- name: distribute encryption config
  template:
    src: encryption_config.yaml.j2
    dest: /var/lib/kubernetes/encryption-config.yaml

- name: Apply scheduler config 
  template:
    src: kube-scheduler.yaml 
    dest: /etc/kubernetes/config/kube-scheduler.yaml
