---
- name: Service fact collectoin
  service_facts: 

- name: Install tools
  apt:
    name: "{{ item }}"
    state: "{{ item.state | default('present') }}"
    update_cache: True
  with_items:
    - net-tools
    - apt-transport-https 
    - ca-certificates 
    - curl
    # - containerd
    # - ebtables
    - nmap

- name: Allow needed ports
  ufw:
    rule: allow
    port: "{{ item.port }}"
    proto: "{{ item.l4_proto | default('tcp') }}"
  with_items:
    - { "port": 22 }
    - { "port": 6443 } # Kubernetes API server
    - { "port": "2379:2380"} # etcd server client API
    - { "port": 10250 } # Kubelet API
    - { "port": 10259 } # kube-scheduler
    - { "port": 10257, proto:	} # kube-controller-manager

- name: Disable SWAP since kubernetes can't work with swap enabled (1/2)
  shell: swapoff -a

- name: br_netfilter for forwarding
  # Not using "community.general.modprobe" because it fails in vagrant
  modprobe:
    name: br_netfilter
    state: present
  register: br_netfilter_module

- name: sysctl -p /etc/sysctl.conf
  shell: sysctl -p /etc/sysctl.conf
  when: br_netfilter_module.changed

# - name: add "sysctl -p /etc/sysctl.conf" to startup
#   lininfile
#     path: /etc/rc.local
#     line: "sysctl -p /etc/sysctl.conf"

- name: Mod networking related files
  shell: 'echo "1" > {{ item }}'
  with_items: 
    - /proc/sys/net/ipv4/ip_forward
    # - /proc/sys/net/bridge/bridge-nf-call-iptable

- name:  Move forward with install if the service doesn't seem to be present
  when: hostvars[inventory_hostname].services['kubelet.service'] is not defined
  block:
    - name: /etc/apt/keyrings is not created by default
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: 755      

    - name: Add the repo as a trusted source 
      shell: > 
        curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.28/deb/Release.key |  
          sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg --yes &&
        echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.28/deb/ /' | 
          sudo tee /etc/apt/sources.list.d/kubernetes.list
      
    - name: Now that we trust it, lets get more stuff installed
      apt:
        name: "{{ item }}"
        state: "{{ item.state | default('present') }}"
        update_cache: True
      with_items:
        - kubelet 
        - kubeadm 
        - kubectl

# # root@master01:/proc/sys/net# sysctl -p /etc/sysctl.conf
# # root@master01:/proc/sys/net# kubeadm init

# # sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config

# master:  kubeadm token create --print-join-command
# sudo cp /etc/kubernetes/admin.conf ~/.kube/config && sudo chown $(id -u):$(id -g) $HOME/.kube/config
