apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
authentication:
  anonymous:
    enabled: false
  webhook:
    enabled: true
  x509:
    clientCAFile: "/var/lib/kubernetes/{{ kube_ca_cert }}"
authorization:
  mode: Webhook
clusterDomain: "cluster.local"
clusterDNS:
  - "10.222.0.10"
podCIDR: "10.200.0.0/16"
resolvConf: "/run/systemd/resolve/resolv.conf"
runtimeRequestTimeout: "15m"
tlsCertFile: "/var/lib/kubelet/{{ kube_node_cert }}"
tlsPrivateKeyFile: "/var/lib/kubelet/{{ kube_node_key }}"
cgroupDriver: "systemd"